# Generated by Django 2.2 on 2021-06-12 10:14

from django.db import migrations, models
import jrfoodadv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JrFoodLabelingAdviseQuestion',
            fields=[
                ('question_id', models.CharField(default=jrfoodadv.models._create_hash_id, max_length=7, primary_key=True, serialize=False, verbose_name='question_id')),
                ('parent_question', models.CharField(max_length=7, null=True, verbose_name='parent_question')),
                ('child_question', models.CharField(max_length=2, null=True, verbose_name='child_question')),
                ('original_data', models.CharField(max_length=126, verbose_name='original_data')),
                ('original_data_num', models.IntegerField(verbose_name='original_data_num')),
                ('textbook_chapter', models.IntegerField(choices=[(0, '食品表示は消費者と事業者をつなぐ架け橋'), (1, '生鮮食品の表示'), (2, '加工食品の表示'), (3, 'いろいろな食品表示の例'), (4, 'その他の食品表示やマーク'), (5, '私たちの食生活について考える')], verbose_name='textbook_chapter')),
                ('question_title', models.CharField(max_length=255, verbose_name='question_title')),
                ('sub_question_title', models.CharField(max_length=255, null=True, verbose_name='sub_question_title')),
                ('question_type', models.CharField(max_length=32, null=True, verbose_name='question_type')),
                ('question_img', models.ImageField(null=True, upload_to='jrfoodadv_images/', verbose_name='question_img')),
                ('choice_a', models.CharField(max_length=126, null=True, verbose_name='choice_a')),
                ('choice_b', models.CharField(max_length=126, null=True, verbose_name='choice_b')),
                ('choice_c', models.CharField(max_length=126, null=True, verbose_name='choice_c')),
                ('choice_d', models.CharField(max_length=126, null=True, verbose_name='choice_d')),
                ('correct_answer', models.CharField(max_length=10, verbose_name='correct_answer')),
                ('commentary', models.CharField(max_length=512, verbose_name='commentary')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'db_table': 'jr_food_labeling_advise_question',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=7, verbose_name='question_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('favorite', models.BooleanField(default=False, verbose_name='favorite')),
                ('memo', models.CharField(max_length=512, verbose_name='memo')),
                ('first_answer', models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, verbose_name='first_answer')),
                ('second_answer', models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, verbose_name='second_answer')),
                ('third_answer', models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, verbose_name='third_answer')),
                ('fourth_answer', models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, verbose_name='fourth_answer')),
                ('fifth_answer', models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, verbose_name='fifth_answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
    ]
