# Generated by Django 2.2 on 2021-06-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrfoodadv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='current_answer',
            field=models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, verbose_name='current_answer'),
        ),
        migrations.AlterField(
            model_name='jrfoodlabelingadvisequestion',
            name='textbook_chapter',
            field=models.IntegerField(choices=[(1, '食品表示は消費者と事業者をつなぐ架け橋'), (2, '生鮮食品の表示'), (3, '加工食品の表示'), (4, 'いろいろな食品表示の例'), (5, 'その他の食品表示やマーク'), (6, '私たちの食生活について考える')], verbose_name='textbook_chapter'),
        ),
        migrations.AlterField(
            model_name='record',
            name='fifth_answer',
            field=models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, null=True, verbose_name='fifth_answer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_answer',
            field=models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, null=True, verbose_name='first_answer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='fourth_answer',
            field=models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, null=True, verbose_name='fourth_answer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.CharField(max_length=512, null=True, verbose_name='memo'),
        ),
        migrations.AlterField(
            model_name='record',
            name='second_answer',
            field=models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, null=True, verbose_name='second_answer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='third_answer',
            field=models.IntegerField(choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, null=True, verbose_name='third_answer'),
        ),
    ]
