# Generated by Django 2.2 on 2021-07-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrfoodadv', '0002_auto_20210613_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='current_choice',
            field=models.CharField(max_length=126, null=True, verbose_name='current_choice'),
        ),
        migrations.AlterField(
            model_name='jrfoodlabelingadvisequestion',
            name='child_question',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='child_question'),
        ),
        migrations.AlterField(
            model_name='jrfoodlabelingadvisequestion',
            name='parent_question',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='parent_question'),
        ),
        migrations.AlterField(
            model_name='jrfoodlabelingadvisequestion',
            name='question_img',
            field=models.ImageField(blank=True, null=True, upload_to='jrfoodadv_img/', verbose_name='question_img'),
        ),
        migrations.AlterField(
            model_name='jrfoodlabelingadvisequestion',
            name='question_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='question_type'),
        ),
        migrations.AlterField(
            model_name='jrfoodlabelingadvisequestion',
            name='sub_question_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='sub_question_title'),
        ),
        migrations.AlterField(
            model_name='record',
            name='fifth_answer',
            field=models.IntegerField(blank=True, choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, null=True, verbose_name='fifth_answer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='fourth_answer',
            field=models.IntegerField(blank=True, choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, null=True, verbose_name='fourth_answer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='memo'),
        ),
        migrations.AlterField(
            model_name='record',
            name='second_answer',
            field=models.IntegerField(blank=True, choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, null=True, verbose_name='second_answer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='third_answer',
            field=models.IntegerField(blank=True, choices=[(0, '未解答'), (1, '不正解'), (2, '正解')], default=0, null=True, verbose_name='third_answer'),
        ),
    ]
