# Generated by Django 3.2 on 2022-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrfoodadv', '0007_auto_20220418_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='later',
            field=models.BooleanField(default=False, verbose_name='later'),
        ),
    ]
