# Generated by Django 3.2 on 2022-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrfoodadv', '0008_record_later'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['user_id'], name='record_user_id_a84bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='timeleft',
            index=models.Index(fields=['user_id'], name='timeleft_user_id_eac8ab_idx'),
        ),
        migrations.AlterModelTable(
            name='record',
            table='record',
        ),
        migrations.AlterModelTable(
            name='timeleft',
            table='timeleft',
        ),
    ]
