version: '3'
services:
  db:
    image: mysql:5.7

    ports:
        - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
    command: sample
  web:
    build: .
    volumes:
      -
    ports:
      - "8000:8000"
    depends_on:
      - db
