# Generated by Django 2.2 on 2021-06-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('payment_course', models.IntegerField(choices=[(0, '無料トライアル'), (1, '初級食品表示診断士'), (2, '中級食品表示診断士')], default=0, verbose_name='payment_course')),
                ('paid_at', models.DateTimeField(null=True, verbose_name='paid_at')),
                ('expired_at', models.DateTimeField(null=True, verbose_name='expired_at')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
    ]
