# Generated by Django 2.2 on 2021-08-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
