# Generated by Django 2.2 on 2021-09-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0004_auto_20210903_0906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
