# Generated by Django 2.2 on 2021-09-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0006_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Information',
        ),
    ]
