# Generated by Django 3.2 on 2022-04-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0009_auto_20211010_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='category',
            field=models.IntegerField(choices=[(1, 'ニュース'), (2, '更新'), (3, 'キャンペーン'), (4, 'プレゼント'), (5, '工事')], null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='information',
            name='release',
            field=models.IntegerField(default=0, verbose_name='release'),
        ),
    ]
