# Generated by Django 3.2 on 2022-05-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0011_auto_20220521_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='category',
            field=models.IntegerField(choices=[(1, 'ニュース'), (4, 'プレゼント'), (2, '更新'), (5, '工事'), (3, 'キャンペーン')], null=True, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='information',
            name='description',
            field=models.CharField(max_length=8192, verbose_name='description'),
        ),
    ]
