# Generated by Django 3.2 on 2022-07-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0013_alter_information_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usercourse',
            index=models.Index(fields=['user_id'], name='usercourse_user_id_a40441_idx'),
        ),
        migrations.AlterModelTable(
            name='usercourse',
            table='usercourse',
        ),
    ]
