# Generated by Django 3.2 on 2022-11-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0017_auto_20221011_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_subject', models.IntegerField(choices=[(1, '食品表示検定・初級'), (2, '食品表示検定・中級')], verbose_name='exam_subject')),
                ('payment_course', models.IntegerField(choices=[(0, 'プラン選択をお願いします'), (1, '初級食品表示診断士コース'), (2, '中級食品表示診断士コース')], default=0, verbose_name='payment_course')),
                ('payment_plan', models.IntegerField(choices=[(1, 'マンスリープラン'), (2, '10Days集中プラン'), (3, '3Daysお試しプラン')], default=0, verbose_name='payment_plan')),
                ('pen_name', models.CharField(max_length=64, verbose_name='pen_name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('exam_date', models.DateTimeField(verbose_name='exam_date')),
                ('points', models.IntegerField(verbose_name='points')),
                ('times', models.CharField(max_length=64, verbose_name='times')),
                ('learning_time', models.CharField(max_length=64, verbose_name='learning_time')),
                ('referenced_site', models.CharField(blank=True, max_length=64, null=True, verbose_name='referenced_site')),
                ('learning_method', models.CharField(max_length=512, verbose_name='learning_method')),
                ('impression', models.CharField(max_length=512, verbose_name='impression')),
                ('advice', models.CharField(max_length=512, verbose_name='advice')),
                ('next_exam', models.CharField(blank=True, max_length=64, null=True, verbose_name='next_exam')),
                ('improvements', models.CharField(blank=True, max_length=512, null=True, verbose_name='next_exam')),
                ('contributor', models.IntegerField(blank=True, null=True, verbose_name='contributor')),
                ('release', models.IntegerField(default=0, verbose_name='release')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='foodadv_payment_course',
            field=models.IntegerField(choices=[(0, 'プラン選択をお願いします'), (1, '初級食品表示診断士コース'), (2, '中級食品表示診断士コース')], default=0, verbose_name='foodadv_payment_course'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='payment_course',
            field=models.IntegerField(choices=[(0, 'プラン選択をお願いします'), (1, '初級食品表示診断士コース'), (2, '中級食品表示診断士コース')], default=0, verbose_name='payment_course'),
        ),
    ]
