# Generated by Django 3.2 on 2022-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0018_auto_20221126_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='improvements',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='improvements'),
        ),
    ]
