# Generated by Django 3.2 on 2022-10-07 14:09

from django.db import migrations, models
import foodadv.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodadvRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=7, verbose_name='question_id')),
                ('user_id', models.IntegerField(verbose_name='user_id')),
                ('favorite', models.BooleanField(default=False, verbose_name='favorite')),
                ('later', models.BooleanField(default=False, verbose_name='later')),
                ('memo', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='memo')),
                ('current_answer', models.IntegerField(choices=[(0, '未実施'), (1, '未解答'), (2, '不正解'), (3, '正解')], default=0, verbose_name='current_answer')),
                ('current_choice', models.CharField(blank=True, max_length=126, null=True, verbose_name='current_choice')),
                ('first_answer', models.IntegerField(choices=[(0, '未実施'), (1, '未解答'), (2, '不正解'), (3, '正解')], default=0, null=True, verbose_name='first_answer')),
                ('second_answer', models.IntegerField(blank=True, choices=[(0, '未実施'), (1, '未解答'), (2, '不正解'), (3, '正解')], default=0, null=True, verbose_name='second_answer')),
                ('third_answer', models.IntegerField(blank=True, choices=[(0, '未実施'), (1, '未解答'), (2, '不正解'), (3, '正解')], default=0, null=True, verbose_name='third_answer')),
                ('fourth_answer', models.IntegerField(blank=True, choices=[(0, '未実施'), (1, '未解答'), (2, '不正解'), (3, '正解')], default=0, null=True, verbose_name='fourth_answer')),
                ('fifth_answer', models.IntegerField(blank=True, choices=[(0, '未実施'), (1, '未解答'), (2, '不正解'), (3, '正解')], default=0, null=True, verbose_name='fifth_answer')),
                ('saved_at', models.DateTimeField(blank=True, null=True, verbose_name='saved_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'db_table': 'foodadv_record',
            },
        ),
        migrations.CreateModel(
            name='FoodadvTimeLeft',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('time_left_at', models.DateTimeField(verbose_name='time_left_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'db_table': 'foodadv_timeleft',
            },
        ),
        migrations.CreateModel(
            name='FoodLabelingAdviseQuestion',
            fields=[
                ('question_id', models.CharField(default=foodadv.models._create_hash_id, max_length=7, primary_key=True, serialize=False, verbose_name='question_id')),
                ('original_data', models.CharField(max_length=126, verbose_name='original_data')),
                ('original_data_num', models.IntegerField(verbose_name='original_data_num')),
                ('textbook_chapter', models.IntegerField(choices=[(1, '食品表示を規定している法の体系'), (2, '生鮮食品の表示'), (3, '加工食品の表示'), (4, '事例でわかる食品表示'), (5, '表示の個別解説'), (6, '栄養成分表示の解説')], verbose_name='textbook_chapter')),
                ('question_title', models.CharField(max_length=255, verbose_name='question_title')),
                ('sub_question_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='sub_question_title')),
                ('question_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='question_type')),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='foodadv_img/', verbose_name='question_img')),
                ('choice_a', models.CharField(max_length=126, null=True, verbose_name='choice_a')),
                ('choice_b', models.CharField(max_length=126, null=True, verbose_name='choice_b')),
                ('choice_c', models.CharField(max_length=126, null=True, verbose_name='choice_c')),
                ('choice_d', models.CharField(blank=True, max_length=126, null=True, verbose_name='choice_d')),
                ('correct_answer', models.CharField(max_length=10, verbose_name='correct_answer')),
                ('commentary', models.CharField(max_length=512, verbose_name='commentary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'db_table': 'food_labeling_advise_question',
            },
        ),
        migrations.AddIndex(
            model_name='foodadvtimeleft',
            index=models.Index(fields=['user_id'], name='foodadv_tim_user_id_f4a78f_idx'),
        ),
        migrations.AddIndex(
            model_name='foodadvrecord',
            index=models.Index(fields=['user_id'], name='foodadv_rec_user_id_e0b36f_idx'),
        ),
    ]
